from dashboard_tutorial.managers.sources import ManagerSources
from dashboard_tutorial.managers.transformers import ManagerTransformer
from dashboard_tutorial.managers.dashboards import ManagerDashboard
from dashboard_tutorial.managers.analysis import ManagerAnalysis