from dashboard_tutorial.sources.source import Source
from dashboard_tutorial.sources.fred_source import FREDSource
from dashboard_tutorial.sources.quandl_source import QuandlSource
from dashboard_tutorial.sources.file_source import FileSource